### ISSUE TITLE
[BUG] Ensure timescaledb user -  'timescaledb_user' is undefined

### ISSUE THREAD

**Issue by mjkl-gh** [idealista/timescaledb_role#1]
### Description

When trying to setup a basic postgresql database with timescaledb and without any variables defined the playbook throws an error at "Ensure timescaledb user":

'timescaledb_user' is undefined

### Steps to Reproduce

1. Setup blank Debian 10 LXC container with ssh configured
2. Create the following playbook:
````
- hosts: postgresql-head.dragundo.net

  roles:
    - postgresql
    - timescaledb

  pre_tasks:
    - name: Update apt cache if needed.
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Ensure sudo is installed
      apt:
        name: sudo
        state: present
````
3. run playbook

**Expected behavior:**
Succesful installation of a default postgresql database with timescaledb

**Actual behavior:**
Error at "Ensure timescaledb user

**Reproduces how often:** 
Everytime

### Environment

- The release version/s you are using: 
- OS: Ubuntu 20.04
- Ansible Version: 2.10.4
- Python Version:3.8.5
- Others:
### Additional Information

[Any additional information, configuration or data that might be necessary to reproduce the issue.]

The defaults do contain `timescaledb_pg_user: "timescaledbuser"` When changing     name: "{{ timescaledb_user }}"` to     name: "{{ timescaledb_pg_user }}" it does work. However, I'm unsure if this was what was intended.

When running with this change the playbook will fail at `timescaledb : TIMESCALEDB | Check if extension is already isntalled.` and `TIMESCALEDB | Create timescaledb extension`  with

`fatal: [postgresql-head.dragundo.net]: FAILED! => {"changed": false, "msg": "unable to connect to database: FATAL:  database \"timescaledb\" does not exist\n"}`

and

`fatal: [postgresql-head.dragundo.net]: FAILED! => {"changed": false, "msg": "unable to connect to database: FATAL:  role \"timescaledbuser\" does not exist\n"}` respectively. 

These errors are a bit expected however, as nothing was actually configured
